services:
  rs:
    image: rust:1.89
    container_name: atcoder-rs
    volumes:
      - ./rs:/workspace
    working_dir: /workspace
    tty: true

  java:
    image: eclipse-temurin:24-jdk
    container_name: atcoder-java
    volumes:
      - ./java:/workspace
    working_dir: /workspace
    tty: true

  ts:
    image: node:22-alpine
    container_name: atcoder-ts
    volumes:
      - ./ts:/workspace
    working_dir: /workspace
    tty: true
    command: sh -c "npm install -g typescript@5.9 ts-node && tail -f /dev/null"