#!/bin/bash
if [ -z "$1" ] || [ -z "$2" ]; then
    echo "使用方法: ./run.sh [rs | java | ts] [フォルダ/ファイル名]"
    exit 1
fi

LANG=$1
FILE=$2

if [ "$LANG" = "rs" ]; then
    if [[ "$FILE" != *\.rs ]]; then FILE="${FILE}.rs"; fi
    mkdir -p rs/src
    cp "rs/$FILE" "rs/src/main.rs"
    docker compose exec rs cargo run

elif [ "$LANG" = "java" ]; then
    if [[ "$FILE" != *\.java ]]; then FILE="${FILE}.java"; fi
    docker compose exec java java "$FILE"

elif [ "$LANG" = "ts" ]; then
    if [[ "$FILE" != *\.ts ]]; then FILE="${FILE}.ts"; fi
    echo "🟦 実行中: TypeScript (ts/$FILE)"
    # コンテナ内のtsフォルダを指定して実行
    docker compose exec ts npx ts-node "$FILE"

else
    echo "エラー: 指定された言語はサポートされていません。"
fi

# ./run ts abs/001
# ./run java abs/001
# ./run rs abs/001